" vim-plug {{{
set nocompatible              " be iMproved, required

if !has('win32')
    set shell=/bin/bash
endif

source ~/.vim/.regexlist.vim

call plug#begin('~/.vim/plugged')

" Git plugin not hosted on GitHub
"Plugin 'git://git.wincent.com/command-t.git'

" {{{ Aesthetics and look & feel
Plug 'vim-airline/vim-airline'                                          " Lean status line
Plug 'vim-airline/vim-airline-themes'
Plug 'bounceme/vim-deep-space'                                          " Color scheme
Plug 'RRethy/vim-illuminate', { 'on': 'IlluminationToggle'}             " illuminate all occurances of word under cursor
Plug 'whatyouhide/vim-lengthmatters', { 'on': 'LengthmattersToggle' }   " Highlight the part of line that doesn't fit into textwidth
Plug 'junegunn/rainbow_parentheses.vim'
Plug 'inside/vim-search-pulse'                                          " Pulse every time we search for next match
" }}}

" {{{ Git helpers
Plug 'zivyangll/git-blame.vim'                                          " Shows a full blown git blame for the entire file
Plug 'whiteinge/diffconflicts'                                          " Convert a 3-way merge to 2-way merge
Plug 'airblade/vim-gitgutter'                                           " Shows a git diff in the 'gutter'
Plug 'Xuyuanp/nerdtree-git-plugin'                                      " Shows git status in nerd tree
Plug 'tpope/vim-rhubarb'                                                " Github plugin
Plug 'iberianpig/tig-explorer.vim'                                      " Use tig from within Vim
" }}}

" {{{ Coding helpers
Plug 'tpope/vim-abolish'                                                " spell abbreviation, substitution, Coercion
Plug 'dense-analysis/ale', { 'on': 'ALEToggle' }                        " Lint
Plug 'vim-scripts/AutoComplPop'
Plug 'jiangmiao/auto-pairs'
Plug 'mbbill/code_complete'
Plug 'junegunn/vim-easy-align'                                          " Easy align
Plug 'ludovicchabant/vim-gutentags'										" auto tags and cscope db
Plug 'skywind3000/gutentags_plus'										" auto tags and cscope db
Plug 'nathanaelkane/vim-indent-guides'                                  " Highlight multiple indents
Plug 'michaeljsmith/vim-indent-object'                                  " Add indent as object
Plug 'scrooloose/nerdcommenter'                                         " Better commenting
Plug 'majutsushi/tagbar'                                                " A class outline viewer for entire project
Plug 'vim-scripts/taglist.vim'                                          " Local file tag list
Plug 'google/yapf', { 'rtp': 'plugins/vim' }                            " reformat range of code
" Plug 'Valloric/YouCompleteMe'
" }}}

" {{{ C coding helper plugins
Plug 'vim-scripts/a.vim'                                                " Switch .c -> .h files quickly
Plug 'FooSoft/vim-argwrap'
Plug 'drmikehenry/vim-headerguard'                                      " Add c++/c header guards
" }}}

" {{{ Python
Plug 'python-mode/python-mode', { 'for': 'python', 'branch': 'develop'  }   " Python IDE
Plug 'vim-scripts/indentpython.vim'                                     " indent python
Plug 'fisadev/vim-isort', { 'for': 'python' }
" }}}

" {{{ Language specifics
Plug 'vim-scripts/HTML-AutoCloseTag', { 'for': 'html' }                 " Automatically insert the closing HTML tag
Plug 'ekalinin/Dockerfile.vim', { 'for': 'dockerfile' }                 " Syntax highlight for Docker file
Plug 'pangloss/vim-javascript', { 'for': 'javascript' }                 " js indent
Plug 'chrisbra/vim-xml-runtime', { 'for': 'xml' }                       " xml ft plugin
" }}}

" {{{ File Utils
Plug 'chrisbra/csv.vim'
Plug 'ctrlpvim/ctrlp.vim'                                               " Fuzzy file finder
Plug 'EinfachToll/DidYouMean'                                           " asks for the right file to open
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --no-bash'  }
Plug 'junegunn/fzf.vim'"
Plug 'vim-scripts/icalendar.vim'                                        " for calendar *.ics files
"Plug 'yegappan/mru'                                                     " most recently used files
Plug 'scrooloose/nerdtree'                                              " NERD Tree file explorer
Plug 'AndrewRadev/undoquit.vim'
" }}}

" {{{ Utils
Plug 'mileszs/ack.vim'                                                  " The search plugin
Plug 'powerman/vim-plugin-AnsiEsc'                                      " ANSI Esc codes in Vim
"Plug 'MattesGroeger/vim-bookmarks'                                      " Bookmarks
Plug 'jkramer/vim-checkbox'                                             " Toggle [ ] [x]
"Plug 'zerowidth/vim-copy-as-rtf'                                        " Copy as RTF (only on OSX)
Plug 'will133/vim-dirdiff'                                              " Diff 2 directories in Vim
Plug 'cmhamill/vim-jrnl'                                                " ft plugin for https://jrnl.sh/
Plug 'sk1418/HowMuch'                                                   " Visual selection total sum
Plug 'junegunn/limelight.vim'
Plug 'AndrewRadev/linediff.vim'                                         " Diff selected blocks
Plug 'inkarkat/vim-mark'                                                " Mark multiple searches with different highlight color
Plug 'xolox/vim-notes', { 'on': 'Note' }                                " Notes from within Vim
Plug 'tpope/vim-obsession'                                              " Vim session management
Plug 'junegunn/vim-peekaboo'
Plug 'krisajenkins/vim-projectlocal'                                    " Local .vimrc
Plug 'glts/vim-radical'                                                 " Convert numbers between decimal, hex, octal and binary
Plug 'xolox/vim-reload'                                                 " Reload Vim plugins when saved
Plug 'tpope/vim-repeat'                                                 " Allow plugins to use '.' for repeat
Plug 'tpope/vim-surround'                                               " Work with delimiters
Plug 'AndrewRadev/switch.vim'                                           " Switch the word under cursor
Plug 'godlygeek/tabular'                                                " Vim script for text filtering and alignment
Plug 'roxma/vim-tmux-clipboard'                                         " Seamless clipboard between vim and tmux
Plug 'tmux-plugins/vim-tmux-focus-events'                               " Restore FocusGained and FocusLost events with tmux
Plug 'christoomey/vim-tmux-navigator'                                   " Seamless navigation between tmux panes and vim splits
Plug 'mbbill/undotree'                                                  " A tree of all undos
Plug 'chrisbra/unicode.vim', { 'on': 'UnicodeToggle' }                  " Unicode Plugin
Plug 'maxbrunsfeld/vim-yankstack'                                       " yank ring
" }}}

" {{{ Dependencies
Plug 'tpope/vim-eunuch'                                                 " Some unix commands to run from within Vim
Plug 'inkarkat/vim-ingo-library'                                        " Dependency for vim-mark plugin
Plug 'glts/vim-magnum'                                                  " Dependency for vim-radical
Plug 'xolox/vim-misc'                                                   " Support plugin for all xolox plugins
" }}}

call plug#end()

" }}} vim-plug
